lib/request.js

`node@0.11.15` was released with a patch that adds support for `path` to url.format (https://github.com/joyent/node/commit/d312b6d15c69cf4c438ed7d884e6396c481a57f6). This means that koa 0.15.0 is effectively incompatible with this node version - the next build on travis will fail for sure without a patch like this.
However, this completely broke `npm install` for git+ssh urls and as such has been reverted on io.js, making it work like on `node@0.11.14` again (https://github.com/iojs/io.js/commit/913addbff5481567262c387cef9594f809e4ef83).
I'm not sure if my solution is acceptable, but it is cross-compatible with `node@0.11.14`/`node@0.11.15`/`io.js@1.0.3`.

Fix url.format taking into account path on node@0.11.15

---

lib/request.js

So I am in this silly quest of cloning the repo, deleting all the code on it and rewriting it again step by step to pass the tests. It is a acceptable way to learn how koa works.
Anyway, I saw that the regex used in `ips` doesn't match the others on the file, so I thought it would be good to change it.

Change request's "ips" regex to match others.

---

Makefile

Hey guys,
I understand that supporting io.js in `.travis.yml ` is a WIP, which surely will make some changes to Makefile, but this commit still makes sense if you need to run `npm test` locally.
However,  the ``` `node -v` == v0* ``` part is ugly. Any better idea? :)
Thanks.

Make `npm test` work with io.js

---

Makefile
lib/application.js
package.json
test/application.js
test/experimental/async.js
test/experimental/index.js

requires `regenerator` or `6to5` to actually use. enabled by setting `app.experimental = true`. it's probably going to be a lot slower. if we merge this, i'd like to get feedback on https://github.com/thenables/composition. maybe add a benchmark with it.
closes https://github.com/koajs/koa/issues/339

add experimental async function support

---

lib/request.js
test/request/host.js
test/request/hostname.js

It will more convenient to use `this.host` as a strict string, like `this.host.split('.')`.
Otherwise we need to detect `this.host` is string or undefined first.
```js
if (typeof this.host === 'string') {
// dosomething ...
} else {
}
```

make sure req.host and req.hostname return strict string

---

lib/request.js
lib/response.js
test/request/charset.js
test/request/type.js
test/response/type.js

not sure if this is look good to everyone, but it reduce lots of code like:
```
(this.charset || '').toLowerCase();
(this.get('ua') || '').indexOf('chrome');
(this.type || '').match(/^text/);
```
and this won't break your app if your are using `!this.get('referer')` etc.

make sure helpers return strict string

---

lib/request.js
test/request/query.js

Before this change, calling request.query when there was no querystring
resulted in a new object created and returned each time. If the resulting
object was ever changed, accessing request.query would not reflect it and
cause weird bugs.

return same object from request.query

---

package.json
test/application.js

Just help to close the #444 in my way, upgrade the `supertest` version and make the test cases be green.
/cc @jonathanong

upgrade supertest to ^1.0.1

---

docs/api/request.md

I ran into the issue from #294 and thought it was a bug since fresh was always returning false. I think it's fair that, at the very least, the docs are not completely clear on how to use `this.fresh`.

Clarify precondition for freshness check

---

test/request/ip.js

Fixes a minor typo in test/request/ip.js (`remoteAddress` instead of `removeAddress`).

Fix typo in test

---

Readme.md

Inspired by my revision here -> https://github.com/elixir-lang/elixir/commit/1932b5243e574bcfff2c4cec2eabc738bc2e43f9
Not everyone uses webchat freenode but it makes a one-click experience for those who do... just like the rest of the links in the section

add a webchat freenode link to irc channel

---

test/application.js

in reference to https://github.com/koajs/koa/pull/485#issuecomment-146035374 @tj

no need to assign error in catch{}-able test

---

Readme.md
benchmarks/experimental/async.js
benchmarks/middleware.js
docs/api/index.md
lib/application.js
test/application/context.js
test/application/index.js
test/application/inspect.js
test/application/onerror.js
test/application/request.js
test/application/respond.js
test/application/response.js
test/application/toJSON.js
test/application/use.js
test/context/cookies.js
test/context/onerror.js
test/context/state.js
test/experimental/async.js
test/helpers/context.js
test/request/href.js
test/request/origin.js
test/response/attachment.js
test/response/status.js

basically #512 without merge conflicts.
i only refactored application into es6 classes. request, response, and context don't really make sense as es6 classes to me since they don't have a constructor, i don't know why you'd `new` them... makes more sense as obj literal / proto to me. making a `new Koa()` does make sense semantically though (well, arguably since you probably wouldn't make multiple of them except in unit tests.. or pass args- sounds like a singleton). 
thoughts?

refactor Application into an es6 class

---

test/helpers/context.js

extension of #513
cleared up other instances of `exports.x` and `exports = x` since it's just misleading when we already have `module.exports` (sometimes in the same file). i.e. we don't know what happens if exports and module.exports export different values + we're in node so module.exports works everywhere- no extra clutter necessary.

no more exports! only module.exports

---

test/response/type.js

Not sure if this is a best way to do it, but we have something similar [10 lines above](https://github.com/koajs/koa/blob/master/test/response/type.js#L48).

Remove TODO from the response type test

---

lib/application.js
test/application/inspect.js
test/application/toJSON.js

As mentioned in #563 we were just missing an initial value and output

fix Application.inspect() – missing .proxy value. Closes #563

---

lib/response.js

#575 - node probably doesn't plan to change this so there's no point of having 'TODO' comment in the code.
Even if they change it it can't be updated without a major version release because it'll not work for node 4 and 5.0.

Remove 'TODO' comment for this.res._headers

---

lib/request.js
test/request/path.js
test/request/querystring.js

`url.path = null` is introduced in https://github.com/koajs/koa/commit/d108926f4634fabe4b18c49ab0ab25a169dbd665
The code rely on `parseurl` will unpredictable when people write some code like `this.path = this.path`.

ensure parseurl always working as expected

---

.eslintrc
Makefile
docs/api/index.md
package.json
test/babel/.babelrc
test/babel/_test.js
test/babel/index.js

test: add a babel example

---

lib/application.js

The comment stated that when 'experimental' is false,
es7 async would be allowed, but the exact opposite is true.

fix(app): fix comment for 'experimental' check

---

.travis.yml

This ensures that Koa is regularly tested against the latest version of Node and surfaces issues early. The main thing is that new version of Node could be released and tests that were previously passing would suddenly start failing (if there were a breaking change) -- as such, tests against stable version of Node are allowed to fail.
I also reversed the order of Node versions in the test matrix so that recent = more relevant versions are at the top.

[CI] Run tests on the stable version of Node

---

Readme.md

Without it one would get: `TypeError: Class constructors cannot be invoked without 'new'`.

Use new operator to create a Koa v2 app

---

docs/guide.md

`appropritaely` → `appropriately`

Fix a typo

---

lib/application.js
package.json
test/context.js
test/context/cookies.js

koa don't change the original request object, need to pass koa's request object to cookies.
(but you can't replace res with response, so this is kind of weird. :(

fix cookies' secure detect

---

docs/error-handling.md

I was thinking about eslint-plugin-markdown, when I realized that I had forgotten to update this when I cherry picked it from master. I guess eslint-plugin-markdown couldn't hurt, but I doubt it would come in handy much. Thoughts?

Update error handling doc to use promises+async (v2.x)

---

Readme.md

I noticed that badges have different styles; having them all elegant suits Koa more.

Unify badges to flat-square style

---

docs/api/context.md

Correct ctx.assert documentation parameter order (v2.x)

---

.travis.yml

These allow for caching, and besides the old ones are deprecated. The only disadvantage to using caching is that once wrk is cached, it won't be updated again until the cache is manually cleared. Hopefully that won't be too big of an issue.

Move to container travis builds

---

test/request/query.js
test/request/querystring.js
test/request/search.js
test/response/attachment.js

I reopened the request and squashed the 3 commits into one commit.

fix to pass the test at node v6.x

---

test/request/query.js
test/request/querystring.js
test/request/search.js

fix the test case to enable koa test pass in node 6.0

fix to pass test under node 6.0.0 

---

AUTHORS
package.json

It's now alphabetically sorted, with info at the top on how to update it. Should we only keep names with spaces in here? (as in, not usernames, just real names) It would leave out some contributors, but we already have the contributors button at the top of the repo; this serves a different purpose.
Also, we have different combinations of usernames, emails, and real names, but there's no good way to unique them independently I think.
I'll make this for v2.x once it's merged for master.

Updated AUTHORS

---

docs/api/index.md

Just saw this and assumed the intent was to use node's `https` module for the second listener.

http.createServer -> https.create... to illustrate "multiple addresses" comment

---

Readme.md

old instructions pointed to incorrect npm module names

fixup babel setup instructions

---

lib/application.js
lib/response.js

1. People should understand javascript's `this`, and it's easy to handle with arrow functions just like `stream.on('error', err => this.onerror(err));`.
2. We already handled all the errors automatically in koa, 99.9% people won't use `this.onerror` in app level. We have written 100+ apps and middlewares in production, no one used `this.onerror`.
3. It's has higher performance(~10% increase).
- before
```
1 middleware
9134.88
5 middleware
9209.45
10 middleware
8261.05
15 middleware
8873.18
20 middleware
8957.63
30 middleware
9036.78
50 middleware
8543.95
100 middleware
8088.44
```
- after
```
1 middleware
9939.28
5 middleware
9806.14
10 middleware
9636.60
15 middleware
9603.57
20 middleware
9664.59
30 middleware
9695.19
50 middleware
9220.74
100 middleware
8498.86
```

[breaking change] don't bind onerror to context

---

docs/guide.md

Very minor, but I think `static` is a reserved word so it might be better to use `serve` instead, I think that's what `koa-static` uses in its examples as well.

doc: Change usage of reserved word `static` in guide

---

docs/api/request.md

It doesn't return `undefined`. It returns `null`. 
https://github.com/jshttp/type-is#each-type-can-be
> `null` will be returned if the request does not have a body.

this.is() returns null when no body is passed

---

docs/api/request.md
test/request/is.js

Modifying the test for `null` from `==` to `===` to make sure it must be `null`.

Amend typo, request.is() return null|fasle|string.

---

lib/request.js
test/request/accepts.js

It returns {String|Array|false}, never return undeifined.
Is the old description a typo? I also look the source code of `accepts` [index.js#L81](https://github.com/jshttp/accepts/blob/master/index.js#L81), seems there is no branch returned a `undefined`. 
```
*     // Accept: text/*, application/json
*     this.accepts('image/png');
*     this.accepts('png');
*     // => undefined
```

Fix typo for accepts().

---

lib/request.js
test/request/charset.js

A malformed content-type header may cause an exception when the charset getter is triggered. This is unexpected as the returning value should always be a string. This can be exploited by bad actors.

Fix malformed content-type header causing exception on charset get

---

lib/request.js
test/request/charset.js

Ported https://github.com/koajs/koa/pull/897 to `v2.x` branch as [requested](https://github.com/koajs/koa/pull/897#issuecomment-279155482).

Fix malformed content-type header causing exception on charset get (v2.x)

---

docs/api/index.md

`app.name` is mentioned in the documentation, but doesn't seem to have any semantic meaning.
Application instances are not frozen and as far as I can tell there's no reason to force people to use `name` specifically (people may want to use `id` / `machineId`, etc., or even better, don't rely on koa app's namespace to pass this information)

remove unused app.name

---

lib/context.js

Let's go the safe path since the ones i removed are now deprecated from `http-errors`.

Removed deprecated ordering of throw arguments

---

lib/application.js

fix: add named arrow function for request and response handlers

---

docs/api/index.md

async/await is not stage-3 feature anymore, it got included to ES2017.
Better advice is to recommend babel `preset-env`. It will enable only the missing features based on the node version in use.

Fix async/await babel recommendation

---

Readme.md
docs/troubleshooting.md

This pulls the really fantastic [Common Problems](https://github.com/koajs/koa/wiki/Common-Problems) wiki page into the main documentation as a troubleshooting guide to give it greater exposure.  I also linked to it from the main read me for the same reason.
I generalized the headings for the two 404 causes after surveying closed tickets to give more surface area in the document for problem diagnosis.
I added an example of a missing `await`, also based on survey of closed tickets.

Add Troubleshooting documentation

---

Readme.md
docs/migration.md
lib/application.js

closes https://github.com/koajs/koa/pull/920

docs: create v2 Migration document

---

.travis.yml

Also prunes modules, so we shouldn't worry about situations where a module not listed in `package.json` is required.

Cache node_modules with Travis

---

.eslintrc.yml

The babel/arrow-parens rule is deprecated. Please use the built in arrow-parens rule instead.
From [log message](https://travis-ci.org/koajs/koa/jobs/215667166#L169)

Remove deprecated babel/arrow-parens

---

docs/api/response.md

Added note about arrays being returned as JSON.

Added note about arrays

---

docs/api/response.md

Just wanted to make a quick doc change based on discussion at koajs/koa#970. Huge fan of this project!
closes #970

docs: Add note about overwriting charset in response.type

---

docs/api/response.md

https://www.ietf.org/rfc/rfc2324.txt clearly identifies status code 418 as a viable HTTP status code.
Also, the underlying `statuses` library does include it as a viable error response code, on line `42` of `codes.json` (https://github.com/jshttp/statuses/blob/master/codes.json#L42). Coincidentally, 42 is the secret to life in the hit book series and film `The Hitchhiker's Guide to the Galaxy`.

Updates documentation to include reference for RFC2324 (HTTP Status 418)

---

docs/api/context.md
docs/api/index.md
docs/api/request.md
docs/api/response.md

Fix some minor inconsistencies in the docs:
* Use arrow functions throughout
* Consistent brace/semicolon/parens style
* Only accept `next` as a parameter if it needs to be called
* Use `async` functions throughout
Let me know if you'd like me to revert an  of these.

improve consistency in api code examples

---

benchmarks/Makefile
benchmarks/middleware.js
benchmarks/run

Add bench mark for async/await.
It will get the benchmark result after run `npm run bench`:
```
> koa@2.3.0 bench /Users/vincent/workspace/github/koa
> make -C benchmarks
1 middleware
10990.91
5 middleware
10840.53
10 middleware
10346.97
15 middleware
10583.24
20 middleware
10470.64
30 middleware
9704.60
50 middleware
10474.31
100 middleware
9840.64
1 async middleware
10117.00
5 async middleware
9967.02
10 async middleware
9472.44
15 async middleware
8081.88
20 async middleware
8474.22
30 async middleware
7557.38
50 async middleware
5732.09
100 async middleware
3859.72
```

add bench for async/await

---

test/application/respond.js

Signed-off-by: Clark Du <clark.duxin@gmail.com>

refactor: remove duplicate assignment in respond test

---

package.json

Since `--fix` always runs, lint on travis does not non-zero exit unless it's "unfixable".

tools: remove --fix to catch lint errors

---

docs/api/index.md

Based on https://github.com/babel/babel/pull/5132, `babel-core/register` is deprecated at babel `v7`. 
So, this pull request fixes babel setup documentation.
Related to #783

Update babel setup

---

package.json

@dlebedynskyi reports in #1085:
> fresh has Vulnerable Regular Expression issue.
https://snyk.io/vuln/npm:fresh:20170908
Current version listed in package.json is 0.5
it is advised to up update to 0.5.2 for fix.
This can be fixed by updating package.json

Update fresh to ^0.5.2 to close vulnerability

---

.mailmap
AUTHORS

In this way mgol's past contribution is mapped correctly.

Update mgol's name in AUTHORS, add .mailmap

---

lib/context.js
test/context/onerror.js

In case when object were thrown error message is really non helpful - you just see `non-error thrown: [object Object]` and stack trace is leads to Koa source. If someone throws an object - it is his fault that no stack trace would be provided, but seen the object itself is already a good start. A specially when it was not your code but some of the modules that you used
With this PR thrown objects would be converted to JSON

Error handling: try to stringify non-error throw if it is an object

---

Readme.md
docs/api/context.md
docs/api/index.md
docs/guide.md
docs/koa-vs-express.md
docs/migration.md

It's Koa.
I think we should have a consistent branding, especially in official docs, hence I have capitalized all K's in word **k**oa (in docs), package names and variables in docs remain untouched of course.

docs: capitalize K in word koa

---

docs/api/index.md

No need for the second 'from', since 'from which' is used.  Insignificant and trivial but hey... always good to clean stuff up, right? 😄

Small grammatical fix in api docs index

---

package.json

Ref https://github.com/facebook/jest/issues/1874
Fixes https://github.com/koajs/koa/issues/1109
The gist: Jest seems to be writing to cache from two different child processes. It's slower, but doesn't really affect Koa.
I'm expecting this to solve flaky travis tests

run coverage using --runInBand, fixes #1109

---

lib/response.js
test/application/respond.js
test/response/flushHeaders.js

from https://github.com/koajs/koa/pull/1078
we should not throw headers sent error to make `ctx.responed` and `ctx.flushHeaders` more safety.

feat: ignore set/remove header/status when header sent

---

lib/application.js
test/application/onerror.js

Cuz AssertionError is not reading-friendly, you could not directly get where the error is emitted.
As TypeError seems better.

Throw a TypeError instead of a AssertionError

---

docs/api/index.md

The way this example is written makes it seem like middleware can't act on the context changes of other middleware.  This updates the logger middleware to use the calculated response time value from the response time middleware instead of calculating it itself.

better demonstrate middleware flow

---

lib/request.js

- Assignment to `proxy` before the `if` block is unnecessary
- When `proto` is falsy then assigned 'http',  calling `split(...)` on the string is unnecessary

Simplify processes in the getter `request.protocol`

---

lib/application.js
lib/context.js
lib/request.js
lib/response.js
test/application/inspect.js
test/context/inspect.js
test/request/inspect.js
test/response/inspect.js

Custom inspection with the `inspect` property is deprecated and will
not work in Node.js 11 anymore. This fixes it by using the custom
inspect symbol where existent and falls back to the old style in case
it does not exist.

fix: use non deprecated custom inspect

---

docs/error-handling.md

Docs incorrectly states that exposed errors are being logged by default error listener:
> which simply log the error if error.expose is true
https://github.com/koajs/koa/blob/master/lib/application.js#L185

Docs: Correct claim about logging exposed errors

---

docs/api/response.md
lib/response.js
test/response/attachment.js

response.attachment require content-disposition, and content-disposition supports option parameter to make some settings, so i hope attachment can also support it.
thanks !

response.attachment append a parameter: options from contentDisposition

---

docs/api/context.md
lib/context.js

Closes: #1261 
I have updated comments/docs to use `status` only as the first param.
Let me know if we should also remove `number` type from the second param of `throw()` function.

doc: updated docs for throw() to pass status as first param.

---

lib/context.js

`res` has been cached at line 130 `const { res } = this;`, so just use it rather `this.res`.

a tiny optimization

---

lib/application.js
test/application/response.js

Addresses #1253 
Logic example for different behaviour depending on http version taken from #1262

Status message is not supported on HTTP/2

---

docs/guide.md

Add `Table of Contents` for guide.md for readable.

chore: add table of contents for guide.md

---

lib/request.js

As we can see the doc of `content-type`: [https://github.com/jshttp/content-type#contenttypeparsereq](https://github.com/jshttp/content-type#contenttypeparsereq), it can deal with the original `req` directly and will also throw TypeError exception when `Content-Type` is missing or invalid. So in my opinion, we don't need `let type = this.get('Content-Type');` to get the type and `if (!type) return ''` to check if the type is unvalid.

use the ability of `content-type` lib directly

---

docs/api/response.md

[#965]: Document other body types

---

Readme.md

Presently, the `README` file has the license information in plain text `MIT`
I made it point to the `License` file which makes more sense 🤔

Add link to the license file 

---

docs/api/index.md

This pull request goes with https://github.com/koajs/koajs.com/pull/38, to turn on the two examples.
Reviewed by @tolmasky.

Activate servers in docs.

---

lib/application.js

It is unnecessary to declare `res` if `ctx.writable === false`

Reduce unnecessary variable declarations

---

lib/response.js
test/response/status.js

Reference, #1119 #1042
This is a different approach to #1119 for allowing custom statuses. Instead of adding an API in Koa on top of statuses, just don't disallow anything unless it's a 3 digit integer.
This is a result from the fact that #1119 [got stale or never got any traction](https://github.com/koajs/koa/pull/1119#issuecomment-457650532), that statuses package can be ~~repopulated~~ added to by its design, [dead-horses comment](https://github.com/koajs/koa/issues/1042#issuecomment-455100429) about RFC and no real purpose to disallow custom statuses, and the fact that I personally dislike previous approaches.

Change set status assert, use statuses when possible

---

Readme.md

> Currently, the `PR welcoming` badge points to the repository itself which doesn't makes sense.
> Updated the link so that it points to creating a new PR.

Update PR-welcoming badge url 

---

docs/api/context.md

I've fixed just a small typo in the doc.

Fix typo in cookie path default value docs

---

docs/api/request.md

Note case-insensitivity for `request.get`, as [docs already do for `response.get`](https://github.com/koajs/koa/blob/master/docs/api/response.md#responsegetfield)

docs: parameter of request.get is case-insensitive

---

docs/api/index.md
lib/application.js
test/application/index.js

Accept an options object on the application constructor to configure app.env, app.proxy, app.keys, and app.subdomainOffset.
https://github.com/koajs/koa/issues/1370

accept options in the Application constructor

---

test/application/respond.js

Setting body will set the content-length header. Unless the
corresponding number of bytes are sent the response will
be aborted and not emit 'end'.

test: fix body test

---

lib/response.js
package.json
test/response/redirect.js

Same bug from express https://github.com/expressjs/express/commit/76eaa326ee8c4dda05568c6452286a16adb84c0b

fix: encode redirect url if not already encoded

---

package.json

This bumps the `cookies` package dependency to add support for `sameSite` cookie attribute value `none`.

feat: support sameSite=none cookies

---

lib/request.js
lib/response.js

Using rest params and validation/concatenating logic is built-in into `type-is`
Also fixes JSDoc declaration

use rest params for request/response .is

---

.codecov.yml
.travis.yml

Enables [partial line coverage](https://docs.codecov.io/docs/node#section-partial-line-coverage) for Codecov and uses faster Bash uploader targeting just one particular file
This will lower reported coverage because CI tests currently runs only on Node >=8 and Koa has some legacy code for earlier versions of Node

enable codecov partial coverage and use bash uploader

---

lib/response.js

Add support for documented since Node >= 12.9 [response.writableEnded](https://nodejs.org/api/http.html#http_response_writableended) property alongside undocumented [response.finished](https://stackoverflow.com/questions/16254385/undocumented-response-finished-in-node-js) used currently.

support `writableEnded`

---

package.json

Updated cookie dependency on v1 branch to support sameSite=none cookies.
This change was already applied to the current (v2) but we needed this same functionality for v1.

feat: support sameSite=none cookies (bump cookies dependency) (#1390)

---

benchmarks/middleware.js
package.json
test/.eslintrc
test/.eslintrc.yml

1. Updates ESLint to the version 6.5.x
2. Updates `eslint-config-standard` to the version 14.x from 7.x. It brings two more required peerDependencies, `eslint-plugin-import` and `eslint-plugin-node`, and the last one if very helpful with Koa tricky `engines`
3. Add explicit extension to the eslint config for tests, lowering newly discovered errors to warning for now, and fixing env from `jest` to `mocha`
4. Fixing lint errors in benchmark.

update ESLint and plugins/configs

---

.travis.yml

This PR removes the no-longer-used Travis setting `sudo: false`. See [more at the Travis blog](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

Drop unused Travis sudo: false directive

---

Readme.md

Hi,
I noticed that the Google+ link doesn't work anymore. Google+ was shutdown for consumers.

docs(links): remove Google+ link

---

docs/api/context.md

Copying from the source document of the cookies module.  In particular, adding in documentation of the sameSite attribute

Updating context.md with the latest cookies opts

---

docs/api/response.md

Hello,
This is a very simple addition to the docs to explicitly document how to return a status code different than 400 when one doesn't set any body in the response.
As a new Koa user (coming from Express) this is a topic that has puzzled me at the beginning. Of course after having used Koa for a little while, the answer seems obvious. But I believe this addition will speed up even more the learning curve.

Document response status with empty body

---

docs/api/index.md

docs(api): add app.use chainability note

---

lib/application.js
lib/response.js
test/application/respond.js
test/application/response.js

Fixes #1446
Either "Content-Length" must be left (resulting in 0) or we need to add "Connection: close" header as well. The former is what it's in this PR, but opinions are welcomed if the later is better.
If approved will add test cases. Usage:
```js
app.use((ctx, next) => {
ctx.body = null; // Must be set first, as this sets status to 204 automatically
ctx.status = 404;
});
```

feat: allow bodyless responses for non empty status codes

---

docs/api/response.md

https://koajs.com/#stream provides the following example on how to handle errors in koa handler:
```
const PassThrough = require('stream').PassThrough;
app.use(async ctx => {
ctx.body = someHTTPStream.on('error', ctx.onerror).pipe(PassThrough());
});
```
but this example is buggy. Consider the following code:
```
const request = require('request');
const { PassThrough } = require('stream');
const Koa = require('koa');
const route = require('koa-route');
function getFile(ctx) {
ctx.body = request
.get('http://asdasd.com/')
.on('error', ctx.onerror)
.pipe(new PassThrough());
}
const init = () => {
const app = new Koa();
app.use(route.get(`/get`, getFile));
app.listen(12345);
};
init();
```
If you will execute `curl http://localhost:12345/get` it will result in exception:
``` …
```

Fixed incorrect example of ctx.onerror usage

---

lib/response.js
package.json
test/response/body.js

The whole `error-inject` functionality (it's [3 lines actually](https://github.com/stream-utils/error-inject/blob/2070e23a55611a19f20e41bd88c3bcbb79b160d2/index.js#L4)) is to add `error` event listener as `on` listener, while **working around the fact that Node doesn't check if that handler already exists**, so, that check was added.
However, by obscuring this logic in 3 lines module even module author @dead-horse probably forgot what exactly his module is doing while introducing #800, which basically rendered this check useless by creating inline function.
To prevent this to happen again, and also taking into account that `ctx.onerror` calls `res.end` and so, `.once` is the more appropriate listener, I'm proposing removing `error-inject` dependency and use the fact that respond body …

remove `error-inject` and fix error handling

---

lib/context.js
test/context/onerror.js

fix: Koa.js handling of node.js set error codes

---

lib/application.js
test/application/onerror.js

Removes two `console.error()` statements that take no arguments and appears only to be used for formatting purposes. To maintain the current formatting this adds a `\n` before and after the logged error message.
This fixes https://github.com/koajs/koa/issues/1470 which reports that `console.error()` statements with no arguments cause noise in AWS Cloudwatch.

Use single console.error() statement in error handler

---

lib/application.js
lib/context.js
test/application/onerror.js
test/context/onerror.js

Improve checks for Error in onerror handlers

---

.gitignore
.travis.yml
package.json
test/load-with-esm.js

Support ESM module.
Fixes: https://github.com/koajs/koa/issues/1469
Refs: https://github.com/addaleax/gen-esm-wrapper

feat: support esm

---

lib/application.js
lib/request.js
lib/response.js
test/application/onerror.js
test/application/respond.js
test/application/use.js
test/context/onerror.js
test/request/accepts.js
test/request/fresh.js
test/request/hostname.js
test/request/length.js
test/request/query.js
test/request/type.js
test/request/whatwg-url.js
test/response/attachment.js
test/response/writable.js

I noticed a handful of small things with regards to spelling and grammar as I've been digging through this code as of recent.  Even though small, I hope this helps.  If these changes seem reasonable, then let me know if you'd like me to take any further action or make adjustments.

chore: fix grammatical and spelling errors in comments and tests

---

docs/api/index.md

Transfer this section to wiki: https://github.com/koajs/koa/wiki/Async-Functions-with-Babel
fix #1386

docs: remove babel ref.

---

docs/api/response.md

fix: https://github.com/koajs/koa/issues/1464

docs: update specific for auto response status

---

Readme.md

https://github.com/koajs/koa/commit/2224cd9b6a648e7ac2eb27eac332e7d6de7db26c removed babel from homepage.
This removes babel-instructions from README.

docs: remove babel from readme

---

docs/error-handling.md
docs/faq.md
docs/guide.md

1. README.md
2. docs/error-handling.md
3. docs/faq.md
4. docs/guide.md

fixed multiple grammatical errors in docs.

---

lib/application.js
test/load-with-esm.js

This is a "fix" I guess to allow TS typings to actually work - according to some other people that actually use TS.
I'm going to need confirmation on both its application, and that this doesn't break anything for Koa v2.

fix: make ESM transpiled CommonJS play nice for TS folks, fix #1513

---

docs/api/index.md

This PR fixes a grammar mistake written on Koa's doc

Fix grammar mistake

---

package.json

Subpath folder mappings will be removed in a future release, so we should use direct subpath patterns instead.
The warning message is like below (with `node-v16.9.0`) when executing `require('koa/lib/response');`:
```bash
(node:80100) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/hyj1991/git/eggjs/egg-core/node_modules/koa/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```
This PR is to be compatible with the omitted specifier path with `require` after fixing **DEP0148**:
```js
require('koa/lib/application');
require('koa/lib/application.js');
require('koa/lib/response'); …
```

fix: nodejs deprecated api <DEP0148>

---

Readme.md

Corrected typo of "KoaJS Slack Grou" to "KoaJS Slack Group"

Corrected typo to line 184 of Readme.md

---

docs/api/context.md
docs/api/index.md
docs/api/request.md
docs/api/response.md
docs/faq.md
docs/koa-vs-express.md

* split sentences
* add commas where needed
* fix various grammar errors
* replace "node.js" with "Node"
* replace "koa" with "Koa"

Fix styling of Koa vs Express docs

---

.github/workflows/node.js.yml
__tests__/application/currentContext.js
__tests__/application/index.js
lib/application.js

pick from https://github.com/koajs/koa/pull/1455
pick from https://github.com/koajs/koa/pull/1718

feat: support asyncLocalStorage

---

lib/application.js

Few extra JSDoc decorations that convey types so end-users of the library get better experience:
Similar to #1607 and [the suggestion](https://github.com/koajs/koa/issues/1607#issuecomment-1172759716) by @jaydenseric except no project changes, just tweaking JSDoc 👍

Provide more typings for application's context and request/response

---

__tests__/application/currentContext.js
lib/application.js

pick from [1757](https://github.com/koajs/koa/pull/1757)

fix: can not get currentContext in error handler

---

docs/api/context.md

Add `ctx.has()`, `ctx.vary()` and `ctx.writable` to the list of response aliases for context. https://github.com/koajs/koa/blob/master/lib/context.js#L199-L216
- ✔ I have ensured my pull request is not behind the main or master branch of the original repository.
- ✔ I have rebased all commits where necessary so that reviewing this pull request can be done without having to merge it first.
- ✔ I have written a commit message that passes commitlint linting.
- ✔ I have ensured that my code changes pass linting tests.
- ✔ I have ensured that my code changes pass unit tests.
- ✔ I have described my pull request and the reasons for code changes along with context if necessary.

docs: add missing entries to response aliases in context.md

---

AUTHORS
docs/koa-vs-express.md
lib/request.js
lib/response.js

When I read Koa's source, I noticed some typo errors in JSDoc and documentation, so I tried to fix them.

fix(lib/doc): fix jsdoc and typo

---

.github/workflows/node.js.yml
__tests__/response/redirect.js
lib/response.js

closes https://github.com/koajs/koa/issues/1800

fix: formatting redirect url on http(s) protocol url

---

__tests__/response/redirect.js
lib/response.js

https://github.com/koajs/koa/issues/1800 's fix https://github.com/koajs/koa/pull/1804 forgot to consider the case where url is uppercase HTTP and HTTPS

fix: handle upper case protocol like HTTP or HTTPS

---

lib/application.js

docs: Modify constructor's options type in the Application class

---

docs/guide.md

This PR is to fix the definition of what a middleware is in `guide.md`. The old definition says that middleware are "simple functions which return a `MiddlewareFunction`", however every other peice of documentation I could find refers to the `MiddlewareFunction` itself as the middleware (not the function that returns the `MiddlewareFunction`).
If the old definition is intentional and correct, I'm happy to close this PR, but it really seems like it's not correct. E.g. the very next sentence says "When the middleware is run, it must manually invoke `next()`", however if a middleware is the function that _returns_ the `MiddlewareFunction` then it wouldn't be able to invoke `next()` since `next` is passed to the `MiddlewareFunction` not the function that returns the `MiddlewareFunction`. …

docs: Fix definition of middleware in guide.md

---

__tests__/application/respond.js
__tests__/response/body.js
lib/application.js
lib/response.js

Feat to handle WHATWG #1777 
I'm open to any suggestions
- [x ] I have ensured my pull request is not behind the main or master branch of the original repository.
- [x ] I have rebased all commits where necessary so that reviewing this pull request can be done without having to merge it first.
- [x ] I have written a commit message that passes commitlint linting.
- [x ] I have ensured that my code changes pass linting tests.
- [x ] I have ensured that my code changes pass unit tests.
- [x ] I have described my pull request and the reasons for code changes along with context if necessary.

feat: add support web WHATWG

---

docs/api/response.md

Fixes #1680.
- [ x I have described my pull request and the reasons for code changes along with context if necessary.

docs: Add writable getter to the response doc

---

__tests__/lib/search-params.js
lib/request.js
lib/search-params.js

Fix #1570 Replace node querystring with URLSearchParams it mimics the way that querystring works

Feat: Replace node querystring with URLSearchParams

---

package.json

Per NodeJS documentation on the `package.json` `exports` object, there seems to be a need for a fallback `default` key:
https://nodejs.org/api/packages.html#conditional-exports
Additionally, I'm seeing things like eslint fail to resolve until a `default` key has been specified. I've not dug any further into why, but I think _some_ default should be defined until more options should later be added.

Added exports.default to package.json

---

package-lock.json
package.json

Closes https://github.com/koajs/koa/issues/1561

:arrow_up: cookies@0.9.1

---

__tests__/application/use.test.js
__tests__/context/throw.test.js
package-lock.json
package.json

- https://github.com/jshttp/http-errors/blob/master/HISTORY.md

deps: update http-errors to v2.0.0

---

__tests__/application/respond.test.js
__tests__/context/onerror.test.js
lib/context.js

This is a huge breaking change as it breaks `fs.createReadStream` support. Instead, you'll have to make sure you'll handle the stream's errors before it reaches the koa response logic. This is good as you'd want to do this for all streams anyways. You can have an upstream middleware like:
```js
app.use(async (ctx, next) {
await next()
// check if the object is a stream
if (ctx.body?.readable && typeof ctx.body?.pipe === 'function') {
await new Promise((resolve, reject) => { // wait for it to be either readable or throw an error
ctx.body.on('readable', () => resolve())
ctx.body.on('error', (err) => reject(err)) // TODO handle errors
})
}
})
```
closes #1420

breaking: remove special ENOENT support

---

docs/guide.md
lib/application.js
package-lock.json
package.json

feat: replace debug module with pure node:util::debuglog

---

__tests__/response/attachment.test.js
lib/response.js

Added security-focused tests to verify:
1. Content-Type is preserved when already set
2. Content-Type is still set when not previously defined (backwards compatibility)
3. The fix prevents XSS vulnerabilities with HTML and SVG files
credit "Luca Carettoni of Doyensec LLC" as [requested in the advisory](https://github.com/koajs/koa/security/advisories/GHSA-c5vw-j4hf-j526).
---

fix: fixes response.attachment behaviour leads to Content-Type Sniffing
