lib/context.js
test/context/onerror.js

non-error thrown, fixed #432

---

docs/api/context.md

Update doc example to use ctx.state

---

test/request/ip.js
test/request/querystring.js

The output from `make test-cov` indicates a few tests are missing, so I filled in the gaps.
Before
```
=============================== Coverage summary ===============================
Statements   : 99.73% ( 371/372 )
Branches     : 99.05% ( 208/210 )
Functions    : 100% ( 81/81 )
Lines        : 100% ( 322/322 )
================================================================================
```
After
```
=============================== Coverage summary ===============================
Statements   : 100% ( 372/372 )
Branches     : 100% ( 210/210 )
Functions    : 100% ( 81/81 )
Lines        : 100% ( 322/322 )
================================================================================
```

Increase test coverage

---

lib/application.js
test/application.js

Solves #447 
// cc participants- @jonathanong @tj @cesarandreu

app.silent option to turn off err logging

---

benchmarks/experimental/async.js
benchmarks/middleware.js

fix benchmarks- cant use const there

---

docs/api/index.md

Fix typo in example for Koa instantiation

---

lib/application.js

Fix param tag on Application.use method

Fix param tag on Application.use method

---

lib/response.js

Standardizes instances of removeHeader to remove

---

Readme.md

change `this` to `ctx` in v2 signature example

---

benchmarks/middleware.js

ESLint now runs fine. This is why we need eslint in travis.

Remove unused http variable (v2.x)

---

Readme.md

TODO: travis should eslint Readme /s

Added semicolons to README v2 alpha example

---

docs/api/index.md

https://github.com/koajs/koa/blob/v2.x/lib/application.js#L173

Docs: v2 error handling is environment independent

---

lib/application.js
lib/request.js
test/helpers/context.js
test/request/ip.js

Cache the request IP

---

docs/error-handling.md

fix: v1 artifact "this" reference

---

Readme.md
docs/guide.md

Small changes I found while browsing the 2.x documentation.

Copy updates

---

docs/api/context.md

add maxAge and overwrite options to ctx.cookies.set(name, value, [options]).

add maxAge and overwrite options api/context doc.

---

docs/api/context.md

add maxAge and overwrite options to ctx.cookies.set(name, value, [options]).

add maxAge and overwrite options api/context doc to master branch.

---

lib/application.js

Fix broken link, fixes #741

---

lib/response.js
test/application.js
test/response/writeable.js

fix(response): correct response.writable logic

---

lib/response.js
test/response/flushHeaders.js

closes #788 
a better way to test this would be nice...
/cc @mufumbo @PlasmaPower @renatopeterman

fix: res.flushHeaders()

---

lib/application.js

Named function is good for APM and avoid anonymous functions everywhere.

fix: add named function for request and response handlers

---

lib/request.js
test/request/subdomains.js

fix: subdomains should be [] if the host is an ip

---

lib/request.js
test/request/subdomains.js

This helps avoid dealing with the port in this.host

fix: should get subdomains from hostname instead

---

lib/application.js
test/application/use.js

This fixes the tense of `will been` to `will be`

nit: fix grammar in generator deprecation warning

---

Readme.md

docs(readme): update reference to latest version

---

docs/api/response.md

Fix response.status default value documentation

---

lib/application.js

Update the link to migration instructions

---

lib/context.js
test/context/onerror.js

cherry-pick from https://github.com/koajs/koa/pull/919

feat: set err.headerSent before app error event emit #919

---

lib/context.js
lib/response.js
test/context/onerror.js
test/response/header.js

closes https://github.com/koajs/koa/pull/925

res: use http.ServerResponse._header when accessors exist 

---

Readme.md

closes https://github.com/koajs/koa/pull/922

readme docs++

---

lib/application.js

The v2.x version of #847, see there for more details.

Return middleware chain promise from `callback()`

---

benchmarks/middleware.js
test/application/respond.js
test/response/body.js
test/response/length.js
test/response/writeable.js

See:
* https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html
* https://nodejs.org/dist/latest-v7.x/docs/api/buffer.html

use Buffer.from instead

---

test/application/use.js

Already covered above
https://github.com/koajs/koa/blob/master/test/application/use.js#L108

remove redudant test case

---

test/request/type.js

change describe to it

---

Readme.md
docs/api/index.md
docs/guide.md
docs/migration.md

Apply `Date.now()` to all docs

---

docs/api/request.md
docs/api/response.md

Update some keyword of doc in official website to match Koa2.
* yield -> await

modified some sample code of doc with wrong keyword (yield -> await)

---

lib/context.js
test/context/inspect.js

Fix context.inspect when called on the prototype

---

docs/koa-vs-express.md

Koa v2 is now using async/await (and promises), right?

koa-vs-express: Update note about generators

---

docs/koa-vs-express.md

Handle routing Express vs Koa.

Koa routing (third party libraries support)

---

test/application/respond.js

Revert "refactor: remove duplicate assignment in respond test"

---

package.json

Remove --forceExit flag for Jest

---

package.json

Relate security issue https://snyk.io/vuln/npm:fresh:20170908

fix: upgrade fresh to the latest version

---

Readme.md

Add Chinese docs link  for v2.x

Add Chinese docs link  for v2.x

---

.eslintrc.yml
package.json

https://github.com/koajs/eslint-config-koa

Use eslint-config-koa

---

lib/response.js
test/response/remove.js
test/response/set.js
test/response/status.js
test/response/vary.js

feat: ignore set/remove header/status when header sent

---

docs/guide.md

Update guide.md (typo)

---

lib/request.js

use this.response.header directly

use this.response insteadof this.ctx.response

---

lib/context.js
test/context/onerror.js

- add test case for 'ENOENT'
- ignore some useless decision logics

test&cov: add test case

---

lib/request.js

- fix comment for api
- ignore useless else cov branch

comment & cov: Fix comment & approve cov

---

lib/request.js
lib/response.js

I added second argument(limit) for split function to performance reason.

Optimize array split

---

Readme.md

I think it's good to have a PR welcoming badge within the `README` file 🤔
As per now I made it to point to the Pr's section.
> But it's a good idea to have a `contributing.md` file to which it should be pointed.

Add PR welcoming badge 

---

docs/guide.md

fs-promise is now deprecated.
Use fs-extra instead.

use 'fs-extra' instead of 'fs-promise'

---

lib/request.js

Consider removing this return statement; it will be ignored.

Consider removing this return statement; it will be ignored.

---

docs/koa-vs-express.md

As per discussion on issue #1335

Removed Document in Progress note in Koa vs Express

---

docs/api/request.md

I spent a few minutes trying to figure out what format the headers were being provided in, perhaps this will save some time for anyone else (or my future self) who forgets the details of how header names are lower-cased and how multiple headers with the same name are combined, etc..

Clarify the format of request.headers

---

docs/api/context.md
docs/api/response.md

Sorry for forgot to update this link in the previous PR.

docs(context): update link

---

package.json
test/application/onerror.js
test/application/respond.js
test/context/onerror.js

test: remove jest and use egg-bin(mocha)

---

docs/api/response.md

https://github.com/koajs/koa/pull/1355#discussion_r302404837

docs: Include `dead-horse`'s comment

---

test/application/respond.js

This fixes a broken test which is cause failure in the Node test suite (https://github.com/nodejs/node/pull/28666).

test: fix end after end

---

docs/api/index.md
docs/api/request.md
lib/application.js
lib/request.js
test/request/ips.js

Security ips

---

docs/api/response.md

docs: fix assert example for response

---

docs/error-handling.md

In this sentence, the subject is the word "using," which acts as a gerund, and not "functions."

correct verb tense in doc

---

docs/api/index.md

doc: app.keys needs to be long enought and random

---

test/response/status.js

test: fix typo in status.js

---

package.json

chore: upgrade koa-convert dependency to ^2.0.0

---

package.json

cherry-pick acb08e0f192fb2692e5dbb6d80dcffd101f2a41c, see https://github.com/koajs/koa/pull/1587

fix: nodejs deprecated api <DEP0148> (#1585)

---

__tests__/application/respond.js
__tests__/context/onerror.js
__tests__/load-with-esm.js
__tests__/response/status.js

Fix all linter warnings

---

__tests__/application/compose.js
__tests__/application/index.js
lib/application.js

Allow the compose function to be configurable

---

package-lock.json
package.json

This reverts commit d2b09439b78fe749a3c68c3cc087cda4c30336f7.

Revert "build(deps-dev): bump jest from 28.1.3 to 29.3.1 (#1709)"

---

lib/application.js

refactor: use asyncLocalStorage.run

---

__tests__/application/index.js
lib/application.js

pick from https://github.com/koajs/koa/pull/1724

fix: should export createAsyncCtxStorageMiddleware function

---

lib/application.js

fix: typo in comment

---

__tests__/application/currentContext.js
lib/application.js

fix: can not get currentContext in error handler

---

docs/api/index.md

update docs/api/index.md:8  `nvm install  7 ` to `nvm install 12`

docs: fix node quickly install with nvm

---

package-lock.json
package.json

Hi all,
This PR will update `cookies@0.9.0` to make the users of koa use CHIPS feature in https://github.com/pillarjs/cookies/pull/152.

feat: bump cookies v0.9.0 for CHIPS

---

.github/workflows/node.js.yml

test: Add Node.js 20

---

__tests__/response/redirect.js
lib/response.js

pick from https://github.com/koajs/koa/pull/1805

fix: handle upper case protocol like HTTP or HTTPS (#1805)

---

lib/response.js

closes https://github.com/koajs/koa/issues/1808

fix: require URL from 'url' module

---

__tests__/application/index.js
lib/application.js

This middleware was made obsolete by e98b8d1.

fix: remove unused async local storage middleware

---

Readme.md

Changehange node.js version in readme.md from 12.x to 18.x

---

package.json

set homepage in package.json

---

lib/application.js

jsdoc of options.asyncLocalStorage

docs: fix asyncLocalStorage comment

---

__tests__/context/toJSON.test.js
__tests__/response/body.test.js
__tests__/response/header.test.js
__tests__/response/inspect.test.js
__tests__/response/set.test.js
lib/response.js
package-lock.json

this is a rebase of https://github.com/koajs/koa/pull/1394. closes #1394

don't coerce header value to string on set #1394 @tinovyatkin
